# Travis-CI Build for DotNetCraft.Common
# see travis-ci.org for details

language: csharp
sudo: required
solution: DotNetCraft.Common.sln

before_install:
  - export EnableNuGetPackageRestore=true

# Make sure build dependencies are installed.
install:
 # - sudo apt-get install -y gtk-sharp2
 - nuget # lets get version number
 - nuget restore DotNetCraft.Common.sln -Verbosity detailed
 - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
 
#cache: 
# - apt
# - directories:
#   - packages

# Run the build script
script:
 - msbuild /p:Configuration=Release DotNetCraft.Common.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Tests/DataAccessLayer.Tests/bin/Release/net461/DataAccessLayer.Tests.dll
 - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Tests/Utils.Tests/bin/Release/net461/Utils.Tests.dll
 - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./Tests/Domain.Tests/bin/Release/net461/Domain.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
